import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import { GitHubLink } from './_components/GitHubLink/GitHubLink';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <header className="flex justify-between p-2 bg-gray-900">
            <h1>Movie Database</h1>
            <GitHubLink />
          </header>
          {children}
        </body>
      </Providers>
    </html>
  );
}
