import type { Metadata } from 'next';
import { Inter, Ubuntu } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import { GitHubLink } from './_components/GitHubLink/GitHubLink';
import clsx from 'clsx';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });
const ubuntu = Ubuntu({ subsets: ['latin'], weight: '500' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={clsx([inter.className, 'min-h-lvh'])}>
          <header className="">
            <div className="max-w-screen-xl flex justify-between px-6 py-2 sm:py-3 ml-auto mr-auto">
              <Link
                href="/"
                className={clsx([
                  ubuntu.className,
                  'text-lg hover:text-orange-500',
                ])}
              >
                Movie Database
              </Link>
              <GitHubLink />
            </div>
          </header>
          {children}
        </body>
      </Providers>
    </html>
  );
}
